services:

  post-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/post_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
      - zookeeper

  postgres:
    image: postgres:15-alpine
    container_name: post-service-db
    environment:
      POSTGRES_DB: post_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54333:5432"
    volumes:
      - post-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    container_name: post-service-redis
    ports:
      - "63800:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: post-service-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: post-service-kafka
    depends_on:
      - zookeeper
    ports:
      - "9999:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2180
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

volumes:
  post-db-data: