server:
  port: 8082

spring:
  profiles:
    active: prod
  application:
    name: feed-service

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: feed_service
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true

  flyway:
    enabled: true
    schemas: feed_service
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: kafka:9092
    listener:
      missing-topics-fatal: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

user-service:
 url: http://user-service:8080